version: "3.8"

services:
  banco:
    image: bitnami/postgresql:13
    container_name: oraculo-banco-tags
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DATABASE_HOST: ${DB_HOST}
    ports:
      - "5430:${DB_PORT}"
    networks:
      - tags-network
    volumes:
      - postgresdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: oraculo-pgadmin-tags
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - banco
    links:
      - banco:${DB_HOST}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - tags-network

  tags:
    container_name: oraculo-tags
    build: .
    restart: always
    depends_on:
      - banco
    networks:
      - tags-network
    links:
      - banco:${DB_HOST}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME} 

volumes:
  node_modules:
  postgresdb:

networks:
  tags-network:
    name: tags-network
    driver: bridge
